- name: Patch Grafana Deployment to install plugins
  k8s:
    state: present
    kind: Deployment
    namespace: monitoring
    name: grafana
    merge_type: strategic-merge-patch
    definition:
      spec:
        template:
          spec:
            containers:
              - name: grafana
                env:
                  - name: GF_INSTALL_PLUGINS
                    value: "grafana-piechart-panel,grafana-clock-panel"

- name: Restart Grafana Deployment
  k8s:
    state: present
    kind: Deployment
    namespace: monitoring
    name: grafana
    wait: yes
