# Root Application - manages all platform and app components in develop
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: develop-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Kobeep/Home_infra.git
    targetRevision: main
    path: gitops/clusters/develop/argocd-apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
