apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-api-deployment
  namespace: api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: infra-api
  template:
    metadata:
      labels:
        app: infra-api
    spec:
      hostNetwork: true
      hostPID: true
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: api-container
          image: ghcr.io/kobeep/home_infra:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: KUBECONFIG
              value: /etc/rancher/k3s/k3s.yaml
          volumeMounts:
            - name: host-root
              mountPath: /host
              readOnly: true
            - name: k3s-config
              mountPath: /etc/rancher/k3s/k3s.yaml
              readOnly: true
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
        - name: k3s-config
          hostPath:
            path: /etc/rancher/k3s/k3s.yaml
            type: File
