apiVersion: ENC[AES256_GCM,data:UGI=,iv:hJN5tohwSrxJG2DwX/XCc1LXnm8jnJYXcJRZFYk9mfE=,tag:xjYJLmiHyRaffBWkyGYYBQ==,type:str]
kind: ENC[AES256_GCM,data:mVEIXx1r,iv:BcK4xy4baU2CUCU896Uav04fR2zQEmXjrVpWQZzUU8U=,tag:tP3evMaPnIOcl6C0kbfvMA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GsOrgmy+3MJ0OuY7kg==,iv:mqvlo7JhjqSNMsgV5FGw7r9p2zVCnG1BTUpEK1cxnHQ=,tag:tJfsu5Y4zcg8ouxN3dzIbw==,type:str]
type: ENC[AES256_GCM,data:3bEw3nGm,iv:q26J8XolFZuCjwlEi3D4ZFKs9LTSCT7xTFecax4Fb3k=,tag:NjOjgxlalusn9mZA6P91aw==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:rxURjMUszcLc/MxxxqrZ2NsG/1byqQVHOw==,iv:0BoTzeVUaoncoeNvyr0muKXbfPY+sQpFNCfp3ngnj7A=,tag:hHa4aRquiB3iFb+L5kXpvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qspcmm9ng5p6rupfjctpthtyxe4l9pdqn9rrsvf2dj09c6tujg8qzvrm3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSkV5cEZmUy81VldSRFR5
            R3lHaWRISDg0VElldDI1NGFNTVR0NExJSGgwCkN2REJyOTd1aFRtY3ZEN0lIRHRD
            QlgrUVd2S0tCcS9teHpFOTVuanpoOGsKLS0tIGlXYUlCdGZ0YWN1WTlPNEp0U3Ry
            QUdtMFhYM1hWZisrNTgreUFocTlzQUEKWqBoYQZhQUVKnjdweM3M17DLe/urDL4z
            B2j7gqEoIM7EOOSSB8WPIUeSFst+HawcKU65eSbrV5q0PYwdE1uj6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T07:51:35Z"
    mac: ENC[AES256_GCM,data:cnSCW/lcM8Jhqy5BAwsO4eUqF8JrHYaShYJHTmtq2ASGm5GdH01Hyt3gywNKqTKUvxPsb7lxRXZ7E5JB93cdr8jLtD4TkvihiaH7pOVg33aC60fOCLy6HwjYu4YD9FAt0uXP8yCIPnPEHD9abfiSoxnYrXnIeeuOa1dEmy6nZdc=,iv:4cWMRbkRDxl6OFYIwkHmQ6Cg5Ci/ghA6scfZ04bxwvk=,tag:kvVWudcCYdWrIRBxop7gqA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
---
apiVersion: ENC[AES256_GCM,data:gn4=,iv:Bk+82XNpprPczc6txnP4scn5d8vxN2IUITElrTJ/yQA=,tag:swjSI1c9NilAnVypvlP4FA==,type:str]
kind: ENC[AES256_GCM,data:XsmBP3rv,iv:801r55vJxJUdxTGnhbgIFctDrfHWbo7lkfYREs6+Mmg=,tag:Gxd66cFo3Cgvxk7eLACquA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CD8x8kAj2LIy0fptJrw=,iv:h99CF95bOac3342G19MzuMLomxGI1CDmgU0naD31mQ0=,tag:n1sAlr+bGCKyFayTY1UR1w==,type:str]
type: ENC[AES256_GCM,data:Jop4Fa4O,iv:Q483yjQdQ9KF4Dizp0YlYg+5bd/l9OwWnAUyDENtMII=,tag:ZPOpq6xh0bKhr42XrTpGuQ==,type:str]
stringData:
    admin-username: ENC[AES256_GCM,data:ufaJ6aI=,iv:QabeSlb8KTpyIdenwDMFHgHxK7vbZmQNyloeaCpfa6A=,tag:HejWVxkoDAy7RQnKinK0gQ==,type:str]
    admin-password: ENC[AES256_GCM,data:l/WTb6SzzfkGwteRpbI16dG8cr47ZHkPQ68=,iv:JucC99DtTasw5G+BuXSa67hfi1gtbv6gIaik09Bue+o=,tag:UNbYKgMGQ4UOgzpKdrk//g==,type:str]
    org: ENC[AES256_GCM,data:BX3nzw==,iv:qp988mb1kRtI4RC1JzQlhsAi4T4Q7WZ7KiQsCbQ1QyM=,tag:V8y8Qgmw48ZqdxBo+r70nw==,type:str]
    bucket: ENC[AES256_GCM,data:x4cCH+Ph0RP3FaJAyw==,iv:sCqoLAzAAbvvhCgEdq3HMMcfkQZcd3ap8sFVbIFNhnE=,tag:0XaWeXId+MilOkEBZ37hmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qspcmm9ng5p6rupfjctpthtyxe4l9pdqn9rrsvf2dj09c6tujg8qzvrm3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSkV5cEZmUy81VldSRFR5
            R3lHaWRISDg0VElldDI1NGFNTVR0NExJSGgwCkN2REJyOTd1aFRtY3ZEN0lIRHRD
            QlgrUVd2S0tCcS9teHpFOTVuanpoOGsKLS0tIGlXYUlCdGZ0YWN1WTlPNEp0U3Ry
            QUdtMFhYM1hWZisrNTgreUFocTlzQUEKWqBoYQZhQUVKnjdweM3M17DLe/urDL4z
            B2j7gqEoIM7EOOSSB8WPIUeSFst+HawcKU65eSbrV5q0PYwdE1uj6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T07:51:35Z"
    mac: ENC[AES256_GCM,data:cnSCW/lcM8Jhqy5BAwsO4eUqF8JrHYaShYJHTmtq2ASGm5GdH01Hyt3gywNKqTKUvxPsb7lxRXZ7E5JB93cdr8jLtD4TkvihiaH7pOVg33aC60fOCLy6HwjYu4YD9FAt0uXP8yCIPnPEHD9abfiSoxnYrXnIeeuOa1dEmy6nZdc=,iv:4cWMRbkRDxl6OFYIwkHmQ6Cg5Ci/ghA6scfZ04bxwvk=,tag:kvVWudcCYdWrIRBxop7gqA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
---
apiVersion: ENC[AES256_GCM,data:OPs=,iv:O8gtbaxnzYoa28TUYFXtLvSaUMDVNPLrWxKGsW5rYgw=,tag:Mun6Ef2NytPRvLTSSB372A==,type:str]
kind: ENC[AES256_GCM,data:b6ti2QH0,iv:Hj1LLh8T1MzKXJBCcTonufeHCd03PyImuf5dW8GYM68=,tag:pMZxY+ldmenMdFznhiz2Hw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MZ6YPHw9JekMy9RVdOy6oNg=,iv:kNf5099ynErvbhhwjuXTTzPsUTAMT+LsuBShWZ25GMc=,tag:Eu3bBGcJOCgSwD7kV1twVA==,type:str]
type: ENC[AES256_GCM,data:XT01x3ur,iv:sDZY5J8tuNBb8RS+9+qjqljA/570qV6GRIfs9UxFxG8=,tag:Uzh3HFItucpTBXD8sgpPIA==,type:str]
stringData:
    openai-api-key: ENC[AES256_GCM,data:+UHL99t80k+8bfi6lwz4Fcp1VQ==,iv:quKqc5ow+OjgxQeY8MCHO9tLYqhDfrqkvn9Nzx6d7mM=,tag:fAKWCl7gbOYS0Sjsv4Qp6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qspcmm9ng5p6rupfjctpthtyxe4l9pdqn9rrsvf2dj09c6tujg8qzvrm3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSkV5cEZmUy81VldSRFR5
            R3lHaWRISDg0VElldDI1NGFNTVR0NExJSGgwCkN2REJyOTd1aFRtY3ZEN0lIRHRD
            QlgrUVd2S0tCcS9teHpFOTVuanpoOGsKLS0tIGlXYUlCdGZ0YWN1WTlPNEp0U3Ry
            QUdtMFhYM1hWZisrNTgreUFocTlzQUEKWqBoYQZhQUVKnjdweM3M17DLe/urDL4z
            B2j7gqEoIM7EOOSSB8WPIUeSFst+HawcKU65eSbrV5q0PYwdE1uj6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T07:51:35Z"
    mac: ENC[AES256_GCM,data:cnSCW/lcM8Jhqy5BAwsO4eUqF8JrHYaShYJHTmtq2ASGm5GdH01Hyt3gywNKqTKUvxPsb7lxRXZ7E5JB93cdr8jLtD4TkvihiaH7pOVg33aC60fOCLy6HwjYu4YD9FAt0uXP8yCIPnPEHD9abfiSoxnYrXnIeeuOa1dEmy6nZdc=,iv:4cWMRbkRDxl6OFYIwkHmQ6Cg5Ci/ghA6scfZ04bxwvk=,tag:kvVWudcCYdWrIRBxop7gqA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
