---
- name: Schedule system update cron job
  cron:
    name: "System update"
    minute: "0"
    hour: "3"
    job: "/usr/bin/apt update && /usr/bin/apt upgrade -y"
    state: present

- name: Schedule Jenkins update cron job
  cron:
    name: "Jenkins update"
    minute: "10"
    hour: "4"
    job: "/usr/local/bin/update-jenkins.sh"
    state: present

- name: Schedule Dashy update cron job
  cron:
    name: "Dashy update"
    minute: "20"
    hour: "4"
    job: "/usr/local/bin/update-dashy.sh"
    state: present

- name: Schedule Home Assistant update cron job
  cron:
    name: "Home Assistant update"
    minute: "30"
    hour: "4"
    job: "/usr/local/bin/update-homeassistant.sh"
    state: present

- name: Schedule Splunk Forwarder restart cron job
  cron:
    name: "Splunk Forwarder restart"
    minute: "0"
    hour: "*/6"
    job: "/usr/local/bin/restart-splunk-forwarder.sh"
    state: present
