jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "Kobeep"
          password: "${KOBEEP_PASSWORD}"

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "devops"
            description: "Full access to Jenkins for DevOps team"
            permissions:
              - "Overall/Administer"
              - "Overall/Read"
            entries:
              - user: "Kobeep"
