jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "Kobeep"
          password: "${KOBEEP_PASSWORD}"

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "devops"
            description: "Full access to Jenkins for DevOps team"
            permissions:
              - "Overall/Administer"
              - "Overall/Read"
            entries:
              - user: "Kobeep"
  clouds:
    - kubernetes:
        name: "kubernetes"
        namespace: "jenkins"
        serverUrl: "https://default.svc"
        skipTlsVerify: true
        jenkinsUrl: "http://cluster.local"
        containerCapStr: "10"
        templates:
          - name: "jenkins-agent"
            label: "jnlp"
            containers:
              - name: "jnlp"
                image: "jenkins/inbound-agent:latest"
                alwaysPullImage: true
                workingDir: "/home/jenkins/agent"
