apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-data
  namespace: home-assistant
spec:
  storageClassName: local-path-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
