---
- name: Deploy Prometheus ConfigMap
  k8s:
    state: present
    definition: "{{ lookup('template', 'prometheus-configmap.yml.j2') | from_yaml }}"

- name: Deploy Prometheus Deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'prometheus-deployment.yml.j2') | from_yaml }}"

- name: Deploy Prometheus Service
  k8s:
    state: present
    definition: "{{ lookup('template', 'prometheus-service.yml.j2') | from_yaml }}"

- name: Deploy Prometheus Ingress
  k8s:
    state: present
    definition: "{{ lookup('template', 'prometheus-ingress.yml.j2') | from_yaml }}"
