controller:
  adminUser: admin
  adminPassword: admin123

  image: "jenkins-custom"
  tag: "latest"

  serviceType: LoadBalancer

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  persistence:
    enabled: true
    size: 8Gi
    storageClass: "local-path"
