---
- name: Add Bitnami repo and deploy Mosquitto
  shell: |
    helm --kubeconfig /root/.kube/config repo add bitnami https://charts.bitnami.com/bitnami || true
    helm --kubeconfig /root/.kube/config repo update
    helm upgrade --install mqtt bitnami/mosquitto \
      --namespace home \
      --create-namespace \
      --set persistence.enabled=true \
      --set persistence.size=5Gi
  args: { warn: false }

- name: Add Cetic repo and deploy Node-RED
  shell: |
    helm --kubeconfig /root/.kube/config repo add cetic https://helm.cetic.github.io/helm-charts || true
    helm --kubeconfig /root/.kube/config repo update
    helm upgrade --install node-red cetic/node-red \
      --namespace home \
      --create-namespace \
      --set persistence.enabled=true \
      --set persistence.size=5Gi
  args: { warn: false }
