---
- name: Create namespace 'home'
  k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: home

- name: Deploy Home Assistant via Helm
  community.kubernetes.helm:
    name: home-assistant
    chart: home-assistant/home-assistant
    namespace: home
    values:
      persistence:
        enabled: true
        size: 10Gi
