---

- name: Ensure namespace "home" exists
  shell: |
    kubectl --kubeconfig /root/.kube/config get namespace monitoring \
      || kubectl --kubeconfig /root/.kube/config create namespace monitoring

- name: Add Home Assistant Helm repo and update
  shell: |
    helm --kubeconfig /root/.kube/config repo add k8s-home-lab \
      https://k8s-home-lab.github.io/helm-charts/ || true
    helm --kubeconfig /root/.kube/config repo update

- name: Deploy Home Assistant via Helm CLI (NodePort)
  shell: >
    helm --kubeconfig /root/.kube/config upgrade --install home-assistant \
      k8s-home-lab/home-assistant \
      --namespace monitoring \
      --create-namespace \
      --set persistence.config.enabled=true \
      --set persistence.config.size=10Gi \
      --set service.main.type=NodePort \
      --set service.main.nodePort=31234
