---
- name: Uninstall old Helm release if present
  shell: >
    helm --kubeconfig /root/.kube/config uninstall home-assistant -n home
  ignore_errors: true

- name: Delete old home-assistant resources in home namespace
  shell: |
    kubectl --kubeconfig /root/.kube/config delete deployment home-assistant svc home-assistant pvc home-assistant-pvc -n home --ignore-not-found
  ignore_errors: true

- name: Ensure namespace "home" exists
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: home

- name: Create Home-Assistant PVC
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: home-assistant-pvc
        namespace: home
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

- name: Deploy Home-Assistant Deployment
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: home-assistant
        namespace: home
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: home-assistant
        template:
          metadata:
            labels:
              app: home-assistant
          spec:
            containers:
              - name: home-assistant
                image: homeassistant/home-assistant:latest
                ports:
                  - containerPort: 8123
                volumeMounts:
                  - name: config
                    mountPath: /config
            volumes:
              - name: config
                persistentVolumeClaim:
                  claimName: home-assistant-pvc

- name: Expose Home-Assistant via NodePort
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: home-assistant
        namespace: home
      spec:
        type: NodePort
        selector:
          app: home-assistant
        ports:
          - port: 8123
            targetPort: 8123
            nodePort: 31234
