---
- name: Create 'home' namespace
  shell: |
    kubectl --kubeconfig /root/.kube/config get namespace home \
      || kubectl --kubeconfig /root/.kube/config create namespace home

- name: Add Home Assistant Helm repo & update
  shell: |
    helm --kubeconfig /root/.kube/config repo add k8s-home-lab \
      https://k8s-home-lab.github.io/helm-charts/ || true
    helm --kubeconfig /root/.kube/config repo update

- name: Deploy Home Assistant
  shell: |
    helm --kubeconfig /root/.kube/config upgrade --install home-assistant \
      k8s-home-lab/home-assistant \
      --namespace home \
      --create-namespace \
      --set persistence.enabled=true \
      --set persistence.size=10Gi
