---
- name: Ensure namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ grocy_namespace }}"
    state: present

- name: Create PVC
  kubernetes.core.k8s:
    state: present
    namespace: "{{ grocy_namespace }}"
    definition: "{{ lookup('template', 'pvc.yml.j2') | from_yaml }}"

- name: Create Deployment
  kubernetes.core.k8s:
    state: present
    namespace: "{{ grocy_namespace }}"
    definition: "{{ lookup('template', 'deployment.yml.j2') | from_yaml }}"

- name: Create Service
  kubernetes.core.k8s:
    state: present
    namespace: "{{ grocy_namespace }}"
    definition: "{{ lookup('template', 'service.yml.j2') | from_yaml }}"

- name: Create Ingress
  kubernetes.core.k8s:
    state: present
    namespace: "{{ grocy_namespace }}"
    definition: "{{ lookup('template', 'ingress.yml.j2') | from_yaml }}"

- name: Wait for deployment rollout
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: "{{ grocy_namespace }}"
    name: "{{ grocy_release_name }}"
  register: grocy_deploy_info
  until: grocy_deploy_info.resources | length > 0 and (grocy_deploy_info.resources[0].status.readyReplicas is defined and grocy_deploy_info.resources[0].status.readyReplicas >= 1)
  retries: 12
  delay: 5
