---
- name: Ensure namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ adguard_namespace }}"
    state: present

- name: Deploy AdGuard Home resources
  kubernetes.core.k8s:
    state: present
    namespace: "{{ adguard_namespace }}"
    definition: "{{ item }}"
  loop: "{{ lookup('template', 'adguard-deployment.yml.j2') | from_yaml_all }}"

- name: Deploy Ingress for AdGuard
  kubernetes.core.k8s:
    state: present
    namespace: "{{ adguard_namespace }}"
    definition: "{{ lookup('template', 'ingress.yml.j2') | from_yaml }}"
