---
- name: Deploy custom iptables rules for Docker and SSH
  template:
    src: iptables.sh.j2
    dest: /usr/local/bin/iptables_docker.sh
    mode: '0755'
  vars:
    cicd_allowed_ips:
      - 192.168.0.122
      - 192.168.0.54
      - 203.0.113.42

- name: Execute Docker chain iptables script
  shell: /usr/local/bin/iptables_docker.sh
  args:
    executable: /bin/bash

- name: Ensure /etc/iptables directory exists
  file:
    path: /etc/iptables
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Save current iptables rules
  command: iptables-save
  register: iptables_rules

- name: Persist iptables rules
  copy:
    dest: /etc/iptables/rules.v4
    content: "{{ iptables_rules.stdout }}"
    owner: root
    group: root
    mode: '0644'
