---
- name: Deploy custom iptables rules for Docker and SSH
  template:
    src: iptables.sh.j2
    dest: /usr/local/bin/iptables_docker.sh
    mode: '0755'
  vars:
    cicd_allowed_ips:
      - 192.168.0.122
      - 192.168.0.54
      - 203.0.113.42

- name: Execute Docker chain iptables script
  shell: /usr/local/bin/iptables_docker.sh
  args:
    executable: /bin/bash

- name: Persist iptables rules
  shell: |
    iptables-save > /etc/iptables/rules.v4
  args:
    creates: /etc/iptables/rules.v4
