- name: Copy AdGuard Home manifest file to the server
  ansible.builtin.template:
    src: adguard-deployment.yml.j2
    dest: /tmp/adguard-deployment.yml
    mode: '0644'

- name: Apply Kubernetes manifest using kubectl
  ansible.builtin.command:
    cmd: kubectl apply -f /tmp/adguard-deployment.yml
  register: kubectl_apply_result
  changed_when: "'configured' in kubectl_apply_result.stdout or 'created' in kubectl_apply_result.stdout"
  failed_when: kubectl_apply_result.rc != 0

- name: Display the result of the kubectl apply operation
  ansible.builtin.debug:
    msg: "{{ kubectl_apply_result.stdout_lines }}"

- name: Deploy Ingress for AdGuard
  k8s:
    state: present
    definition: "{{ lookup('template', 'ingress.yml.j2') | from_yaml }}"
