apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - issuer.yaml

secretGenerator:
  - name: homelab-ca-secret
    namespace: cert-manager
    files:
      - tls.crt=ca/rootCA.crt
      - tls.key=ca/rootCA.key
    type: kubernetes.io/tls
