def branches = ['main', 'develop']

def playbooksDir = new File('ansible/playbooks')
def playbookChoices = playbooksDir.exists()
    ? playbooksDir.listFiles({ f -> f.name.endsWith('.yml') } as FileFilter)*.name.sort()
    : ['NO_PLAYBOOKS_FOUND']

def kubectlChoices = [
    'get pods -A',
    'get services -A',
    'describe pod <pod-name>'
]

branches.each { branch ->

    pipelineJob("home_infra-${branch}") {
        description("Generated pipeline for branch: ${branch} (auto-generated by seed-upstream.groovy)")

        parameters {
            choiceParam('ACTION', ['Run Ansible Playbook', 'Execute Kubectl Command'], 'What do you want to run?')
            choiceParam('PLAYBOOK', playbookChoices, 'Playbook to run (only used if ACTION = Run Ansible Playbook)')
            choiceParam('KUBECTL_COMMAND', kubectlChoices, 'kubectl command (only used if ACTION = Execute Kubectl Command)')
            stringParam('POD_NAME', '', 'Pod name — only needed for "describe pod <pod-name>"')
        }

        definition {
            cpsScm {
                scm {
                    git {
                        remote {
                            url('https://github.com/Kobeep/home_infra.git')
                            credentials('github')
                        }
                        branches("*/${branch}")
                    }
                }
                scriptPath('jenkins/Jenkinsfile')
                lightweight(true)
            }
        }

        logRotator {
            numToKeep(10)
            daysToKeep(7)
        }
    }
}
