def branchList = ['main', 'develop']

def playbookChoices = readFileFromWorkspace('playbook-manifest.txt')
    .readLines()
    *.trim()
    .findAll { it }

def kubectlChoices = [
    'get pods -A',
    'get services -A',
    'describe pod <pod-name>'
]

def inventoryFile = 'ansible/inventory.yml'

// get ip address from inventory file
def serverIP = new File(inventoryFile).readLines()
    .find { it.startsWith('homelab') }
    ?.split(' ')[1]
    ?.trim()

def playbookChoicesLiteral = "[" + playbookChoices.collect { "'${it}'" }.join(', ') + "]"
def kubectlChoicesLiteral = "[" + kubectlChoices.collect { "'${it}'" }.join(', ') + "]"

branchList.each { branch ->

    pipelineJob("home_infra-${branch}") {
        description("Generated pipeline for branch: ${branch} (auto-generated by upstream.groovy)")

        parameters {
            choiceParam('ACTION', ['Run Ansible Playbook', 'Execute Kubectl Command'], 'What do you want to run?')

            activeChoiceReactiveParam('PLAYBOOK') {
                description('Playbook to run — only relevant if ACTION = Run Ansible Playbook')
                choiceType('SINGLE_SELECT')
                filterable()
                groovyScript {
                    script("""
                        if (ACTION == 'Run Ansible Playbook') {
                            return ${playbookChoicesLiteral}
                        } else {
                            return ['N/A']
                        }
                    """)
                    fallbackScript('return ["ERROR"]')
                }
                referencedParameter('ACTION')
            }
            activeChoiceReactiveParam('KUBECTL_COMMAND') {
                description('kubectl command — only relevant if ACTION = Execute Kubectl Command')
                choiceType('SINGLE_SELECT')
                groovyScript {
                    script("""
                        if (ACTION == 'Execute Kubectl Command') {
                            return ${kubectlChoicesLiteral}
                        } else {
                            return ['N/A']
                        }
                    """)
                    fallbackScript('return ["ERROR"]')
                }
                referencedParameter('ACTION')
            }

            stringParam('POD_NAME', '', 'Pod name — only needed for "describe pod <pod-name>"')
        }
        definition {
            cpsScm {
                    git {
                        remote {
                            url('https://github.com/Kobeep/home_infra.git')
                            credentials('github')
                        }
                        branches("*/${branch}")
                    }
                }
                scriptPath('jenkins/Jenkinsfile')
                lightweight(true)
            }
        }

        logRotator {
            numToKeep(10)
            daysToKeep(7)
        }
    }
}
