apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  namespace: grocy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocy
  template:
    metadata:
      labels:
        app: grocy
    spec:
      containers:
      - name: grocy
        image: linuxserver/grocy:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /config
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Warsaw"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: grocy-data
