all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=60s'
  hosts:
    server:
      ansible_host: 192.168.1.100
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/server/id_rsa
    hpserver:
      ansible_host: 192.168.0.122
      ansible_user: hpserver
      ansible_ssh_private_key_file: ~/.ssh/hpserver/id_rsa
