all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=60s'
    ansible_ssh_private_key_file: "/root/.ssh/{{ inventory_hostname }}/id_rsa"
  hosts:
    mainserver:
      ansible_host: 192.168.1.100
      ansible_user: ubuntu
    hpserver:
      ansible_host: 192.168.0.122
      ansible_user: hpserver
    szymonpc:
      ansible_host: 192.168.0.154
      ansible_user: szymopc
    kubapc:
      ansible_host: 192.168.0.54
      ansible_user: jakubpospieszny
