---
- name: Provision home Kubernetes cluster with Dashy, Home Assistant & Grafana
  hosts: server
  become: true
  collections:
    - community.kubernetes   # now we can use 'helm'
  vars:
    k3s_version: v1.26.5+k3s1                   # adjust as desired
    helm_version: v3.12.2                        # adjust as desired
    kubeconfig_dest: "/root/.kube/config"
    namespaces:
      - home
      - monitoring
    apps:
      - name: dashy
        chart: dashy/dashy
        namespace: monitoring
        values:
          service:
            type: NodePort
            port: 80
          ingress:
            enabled: false
      - name: grafana
        chart: stable/grafana
        namespace: monitoring
        values:
          adminUser: admin
          adminPassword: SuperSecret123
          service:
            type: NodePort
          persistence:
            enabled: true
            size: 5Gi
      - name: home-assistant
        chart: home-assistant/home-assistant
        namespace: home
        values:
          persistence:
            enabled: true
            size: 10Gi

  tasks:
    - name: Install prerequisites (curl, apt-transport-https)
      apt:
        name:
          - curl
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Install K3s via official install script
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure K3s service is enabled and running
      systemd:
        name: k3s
        enabled: true
        state: started

    - name: Copy Kubeconfig for root user
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ kubeconfig_dest }}"
        owner: root
        group: root
        mode: '0600'

    - name: Install kubectl (k3s ships its own, but this makes it available in PATH)
      apt:
        name: kubectl
        state: present

    - name: Download Helm tarball
      get_url:
        url: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
        dest: /tmp/helm.tar.gz

    - name: Extract Helm binary
      unarchive:
        src: /tmp/helm.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Move Helm into /usr/local/bin
      copy:
        src: /tmp/linux-amd64/helm
        dest: /usr/local/bin/helm
        mode: '0755'

    - name: Add Helm repositories
      shell: |
        helm repo add stable https://charts.helm.sh/stable
        helm repo add home-assistant https://home-assistant.github.io/helm-charts
        helm repo add dashy https://lissy93.github.io/charts
        helm repo update
      args:
        creates: /root/.cache/helm/repository/repositories.yaml

    - name: Create Kubernetes namespaces
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ item }}"
      loop: "{{ namespaces }}"

    - name: Deploy applications via Helm
      helm:
        name: "{{ item.name }}"
        chart: "{{ item.chart }}"
        namespace: "{{ item.namespace }}"
        create_namespace: false
        values: "{{ item.values }}"
      loop: "{{ apps }}"
