---
- name: Install K3s and configure kubectl
  hosts: server
  become: true
  vars:
    kubeconfig_dest: "/root/.kube/config"

  tasks:
    - name: Install prerequisites (curl, apt-transport-https)
      apt:
        name:
          - curl
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Install K3s via official install script
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Enable and start K3s
      systemd:
        name: k3s
        enabled: true
        state: started

    - name: Ensure remote ~/.kube directory exists
      file:
        path: /root/.kube
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Copy kubeconfig to root
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ kubeconfig_dest }}"
        owner: root
        group: root
        mode: '0600'
        remote_src: yes
