---
- name: Install K3s and configure kubectl
  hosts: server
  become: true
  vars:
    k3s_version: v1.26.5+k3s1
  tasks:
    - name: Install prerequisites
      apt:
        name: [curl, apt-transport-https]
        update_cache: yes

    - name: Install K3s
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Enable and start K3s
      systemd:
        name: k3s
        enabled: true
        state: started

    - name: Copy kubeconfig to root
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /root/.kube/config
        mode: '0600'

    - name: Ensure kubectl is available
      apt:
        name: kubectl
        state: present

    - name: Ensure Helm repositories are added
      shell: |
        helm repo add stable https://charts.helm.sh/stable
        helm repo add home-assistant https://home-assistant.github.io/helm-charts
        helm repo add dashy https://lissy93.github.io/charts
        helm repo update
      args:
        creates: /root/.cache/helm/repository/repositories.yaml
