---
- name: Install K3s and configure kubectl
  hosts: server
  become: true
  pre_tasks:
    - name: Install python3-pip on server
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install Python Kubernetes client library
      pip:
        name: kubernetes
        executable: pip3
  vars:
    kubeconfig_dest: /root/.kube/config

  tasks:
    - name: Install prerequisites (curl, apt-transport-https)
      apt:
        name:
          - curl
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Install K3s via official script
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure K3s service is running
      systemd:
        name: k3s
        enabled: true
        state: started

    - name: Ensure remote ~/.kube exists
      file:
        path: /root/.kube
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Copy K3s kubeconfig to root
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ kubeconfig_dest }}"
        owner: root
        group: root
        mode: '0600'
        remote_src: yes

    - name: Install Helm (download & extract)
      shell: |
        set -e
        helm_version="v3.12.2"
        curl -fsSL https://get.helm.sh/helm-${helm_version}-linux-amd64.tar.gz \
          -o /tmp/helm.tar.gz
        tar -zxC /tmp -f /tmp/helm.tar.gz
        mv /tmp/linux-amd64/helm /usr/local/bin/helm
      args:
        creates: /usr/local/bin/helm

    - name: Add stable Helm repo
      shell: |
        helm repo add stable https://charts.helm.sh/stable || true
        helm repo update
      args:
        creates: /root/.cache/helm/repository/repositories.yaml
