---
- import_playbook: k3s.yml

- name: Provision server with base tools and applications
  hosts: server
  become: true
  vars_files:
    - group_vars/all/vault.yml
  pre_tasks:
    - name: Install python3-pip and Kubernetes client package
      apt:
        name:
          - python3-pip
          - python3-kubernetes
        state: present
        update_cache: yes
  roles:
    - tools/docker
    - tools/helm
    - tools/kubectl
    - apps/oh_my_zsh
    - server/jenkins

  tasks:
    - name: Deploy Home Assistant to K3S
      include_role:
        name: server/home_assistant

    - name: Deploy Dashy to K3S
      include_role:
        name: server/dashy

    - name: Deploy Grafana to K3S
      include_role:
        name: server/grafana

    - name: Deploy Influxdb to K3S
      include_role:
        name: server/influxDB

    - name: Ingress
      include_role:
        name: server/ingress

    - name: Deploy OpenWebUI to K3S
      include_role:
        name: server/openwebui

    # - name: Deploy AdGuard to K3S
    #   include_role:
    #     name: server/adguard

    # - name: Configure firewall rules
    #   include_role:
    #     name: server/firewall
