---
- name: Provision server with Home Assistant, Dashy, and Grafana
  hosts: mainserver
  become: true
  roles:
    - tools/docker
    - tools/helm
    - server/home_assistant
    - server/dashy
    - server/grafana
    - firewall
