---
- import_playbook: k3s.yml

- name: Provision server with base tools and applications
  hosts: server
  become: true

  roles:
    - tools/docker
    - apps/helm
    - apps/kubectl
    - apps/oh_my_zsh

  tasks:
    - name: Ensure .kube directory exists
      file:
        path: /root/.kube
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Deploy Home Assistant role
      include_role:
        name: server/home_assistant

    - name: Deploy Dashy role
      include_role:
        name: server/dashy

    - name: Deploy Grafana role
      include_role:
        name: server/grafana

    - name: Configure firewall rules
      include_role:
        name: server/firewall
