---
- import_playbook: k3s.yml

- name: Provision server with base tools and applications
  hosts: server
  become: true
  pre_tasks:
    - name: Install python3-pip and Kubernetes client package
      apt:
        name:
          - python3-pip
          - python3-kubernetes
        state: present
        update_cache: yes
  roles:
    - tools/docker
    - tools/helm
    - tools/kubectl
    - apps/oh_my_zsh

  tasks:
    - name: Deploy Home Assistant role
      include_role:
        name: server/home_assistant

    - name: Deploy Dashy role
      include_role:
        name: server/dashy

    - name: Deploy Grafana role
      include_role:
        name: server/grafana

    - name: Configure firewall rules
      include_role:
        name: server/firewall

    - name: Ingress
      include_role:
        name: server/ingress
