---
- name: Deploy Kubernetes cluster (k3s)
  import_playbook: k3s.yml

- name: Provision server with Home Assistant, Dashy, and Grafana
  hosts: server
  become: true
  roles:
    - tools/docker
    - apps/helm
    - apps/kubectl
    - apps/oh_my_zsh
    - server/home_assistant
    - server/dashy
    - server/grafana
    - server/firewall
