---
- name: Provision server with Home Assistant, Dashy, and Grafana
  hosts: server
  become: true
  roles:
    - roles/tools/docker
    - roles/tools/helm
    - roles/server/home_assistant
    - roles/server/dashy
    - roles/server/grafana
