---
- name: Include a playbook for including arch specifc vars
  import_playbook: vars.yml

- name: Fedora test
  hosts:
    - "{{ hosts_to_deploy | default('local') }}"
  become: true
  gather_facts: true
