---
- name: Install applications using Chocolatey
  hosts: windows
  gather_facts: yes
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        state: present

    - name: Install applications
      win_chocolatey:
        name: "{{ item }}"
        state: present
      loop:
        - googlechrome
        - battlenet
        - curseforge
        - eaapp
        - epicgameslauncher
        - metatft
        - riotclient
        - steam
        - ubisoftconnect
        - discord
        - spotify
        - vlc
