---
- name: Ensure namespace "monitoring" exists
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring

- name: Add InfluxData Helm repo (idempotent)
  shell: |
    helm --kubeconfig /root/.kube/config repo add influxdata https://helm.influxdata.com || true
    helm --kubeconfig /root/.kube/config repo update

- name: Deploy InfluxDB via Helm CLI
  shell: |
    helm --kubeconfig /root/.kube/config upgrade --install influxdb influxdata/influxdb \
      --namespace monitoring \
      --create-namespace \
      --wait --timeout 120s \
      --set persistence.enabled=true \
      --set persistence.size=5Gi \
      --set auth.enabled=true \
      --set auth.adminUser=hauser \
      --set auth.adminPassword=SuperSecretInflux123 \
      --set service.type=ClusterIP

- name: Create database and grant privileges in InfluxDB
  shell: |
    kubectl --kubeconfig /root/.kube/config -n monitoring exec svc/influxdb -- \
      influx -execute "CREATE DATABASE home_assistant"
    kubectl --kubeconfig /root/.kube/config -n monitoring exec svc/influxdb -- \
      influx -execute "GRANT ALL ON home_assistant TO hauser"
