---
grocy_namespace: grocy
grocy_release_name: grocy
grocy_image: "linuxserver/grocy:4.5.0"
grocy_replicas: 1

grocy_storage_size: "2Gi"
grocy_pvc_name: grocy-data
grocy_mount_path: /config

grocy_service_name: grocy
grocy_service_port: 80
grocy_container_port: 80

grocy_host: grocy.kobeeq.eu
grocy_ingress_name: grocy-ingress
grocy_ingress_class: traefik
grocy_tls_secret: grocy-tls

grocy_resources: {}

grocy_env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: TZ
    value: "Europe/Warsaw"
