---
- name: Create namespace 'monitoring'
  k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring

- name: Deploy Dashy via Helm
  community.kubernetes.helm:
    name: dashy
    chart: dashy/dashy
    namespace: monitoring
    values:
      service:
        type: NodePort
        port: 80
      ingress:
        enabled: false
