---
- name: Create 'monitoring' namespace
  shell: |
    kubectl --kubeconfig /root/.kube/config get namespace monitoring \
      || kubectl --kubeconfig /root/.kube/config create namespace monitoring

- name: Add Dashy Helm repo & update
  shell: |
    helm --kubeconfig /root/.kube/config repo add dashy \
      https://lissy93.github.io/charts || true
    helm --kubeconfig /root/.kube/config repo update

- name: Deploy Dashy
  shell: |
    helm --kubeconfig /root/.kube/config upgrade --install dashy \
      dashy/dashy \
      --namespace monitoring \
      --create-namespace
