---
- name: Create namespace 'monitoring'
  shell: |
    kubectl --kubeconfig /root/.kube/config create namespace monitoring || true

- name: Add Dashy Helm repo
  shell: |
    helm repo add dashy https://lissy93.github.io/charts || true
    helm repo update

- name: Deploy Dashy via Helm CLI
  shell: |
    helm --kubeconfig /root/.kube/config upgrade --install dashy dashy/dashy \
      --namespace monitoring \
      --create-namespace \
      --set service.type=NodePort \
      --set service.port=80 \
      --set ingress.enabled=false
