ollama_namespace: ai
ollama_model: llama3.1:13b-q4_K_M
ollama_ingress_host: "ai.kobeeq.eu"
gpt3o_api_key: "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"
