---
- name: Print macOS role selection
  ansible.builtin.debug:
    msg: "macOS workstation role selected for Kobeep"

- name: Ensure core cloud tooling is present
  community.general.homebrew:
    name:
      - kubectl
      - helm
      - k9s
      - stern
      - terraform
      - awscli
      - azure-cli
      - docker
    state: present
  when: ansible_system == 'Darwin'
