---
- name: Create Traefik Ingress for Monitoring Services
  k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: home-services-ingress
        namespace: monitoring
      spec:
        ingressClassName: traefik
        rules:
          - host: dashy.kobeeq.eu
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: dashy
                      port:
                        number: 80
          - host: grafana.kobeeq.eu
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: grafana
                      port:
                        number: 80

- name: Create Traefik Ingress for Home Assistant
  k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: home-assistant-ingress
        namespace: home
      spec:
        ingressClassName: traefik
        rules:
          - host: ha.kobeeq.eu
            http:
              paths:
                - path: /dashboard-kobee/0
                  pathType: Prefix
                  backend:
                    service:
                      name: home-assistant
                      port:
                        number: 8123
