all:
  children:
    infra:
      children:
        server:
          hosts:
            ubuntu:
              ansible_host: 192.168.1.16
              ansible_user: server
              ansible_ssh_private_key_file: ~/.ssh/server/id_rsa
        modem:
          hosts:
            funbox:
              ansible_host: 192.168.1.1  # mac: 3C:F0:83:BB:99:10
            samsung-washer:
              ansible_host: 192.168.1.10  # mac: 28:6B:B4:6E:0D:0A
            wmpf4qwtc6:
              ansible_host: 192.168.1.25  # mac: 8C:3B:4A:41:F7:EC
    clients:
      children:
        pc:
          hosts:
            fedora:
              ansible_host: 192.168.1.31
        phone:
          hosts:
            iphone:
              ansible_host: 192.168.1.18  # mac: B6:61:91:15:1C:76
