apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-sa
  namespace: backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-role
  namespace: backup
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-rolebinding
  namespace: backup
subjects:
- kind: ServiceAccount
  name: backup-sa
  namespace: backup
roleRef:
  kind: Role
  name: backup-role
  apiGroup: rbac.authorization.k8s.io
