---
- name: Install K3s and configure kubectl
  hosts: server
  become: true

  vars:
    kubeconfig_dest: /root/.kube/config

  tasks:
    - name: Install prerequisites (curl, apt-transport-https)
      apt:
        name:
          - curl
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Install K3s via official script
      script: "{{ playbook_dir }}/../ansible/scripts/install_k3s.sh -- "

    - name: Ensure K3s service is running
      systemd:
        name: k3s
        enabled: true
        state: started

    - name: Ensure remote ~/.kube exists
      file:
        path: /root/.kube
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Copy K3s kubeconfig to root
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ kubeconfig_dest }}"
        owner: root
        group: root
        mode: '0600'
        remote_src: yes

    - name: Install Helm (download & extract)
      script: "{{ playbook_dir }}/../ansible/scripts/install_helm.sh"

    - name: Add stable Helm repo
      script: "{{ playbook_dir }}/../ansible/scripts/helm_repo_update.sh stable https://charts.helm.sh/stable"
      args:
        creates: /root/.cache/helm/repository/repositories.yaml
