apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:2.7
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: storage
          mountPath: /var/lib/influxdb2
        env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: "setup"
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: "admin"
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: "adminpassword"
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: "homelab"
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: "metrics"
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: influxdb-data
