server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: local-ca
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: vault.192.168.1.24.nip.io
        paths: []
    tls:
      - secretName: vault-tls
        hosts:
          - vault.192.168.1.24.nip.io
  dataStorage:
    enabled: true
    size: 5Gi
  standalone:
    enabled: true
ui:
  enabled: true
