
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  purge_keep_days: 7
  db_url: influxdb://hauser:SuperSecretInflux123@influxdb.monitoring.svc.cluster.local:8086/home_assistant

influxdb:
  host: influxdb.monitoring.svc.cluster.local
  port: 8086
  database: home_assistant
  username: hauser
  password: SuperSecretInflux123
  default_measurement: state
  include:
    entities:
      - light.led_bulb_w509z2
      - light.lsc_smart_a60_rgb_cct
      - light.lsc_smart_a60_rgb_cct_2
      - light.lsc_smart_a60_rgb_cct_3
      - switch.lsc_smart_power_plug_socket_1
