
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.influxdb: debug

recorder:
  purge_keep_days: 7  

influxdb:
  host: influxdb.monitoring.svc.cluster.local
  port: 8086
  database: home_assistant
  username: hauser
  password: SuperSecretInflux123
  default_measurement: state
  include:
    entities:
      - light.led_bulb_w509z2
      - light.lsc_smart_a60_rgb_cct
      - light.lsc_smart_a60_rgb_cct_2
      - light.lsc_smart_a60_rgb_cct_3
      - switch.lsc_smart_power_plug_socket_1
      - sensor.system_monitor_processor_use
      - sensor.system_monitor_memory_usage
      - sensor.system_monitor_disk_usage
