apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opengrok-data
  namespace: opengrok
spec:
  storageClassName: local-path-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
