---
- name: Create directory for Jenkins CI/CD
  ansible.builtin.file:
    path: "{{ jenkins_base_dir }}"
    state: directory
    owner: "{{ jenkins_owner }}"
    group: "{{ jenkins_group }}"
    mode: '0755'
    recurse: true

- name: Copy docker-compose.yml
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ jenkins_base_dir }}/docker-compose.yml"
    owner: "{{ jenkins_owner }}"
    group: "{{ jenkins_group }}"
    mode: '0644'

- name: Copy Jenkins Dockerfile
  ansible.builtin.copy:
    src: Dockerfile
    dest: "{{ jenkins_base_dir }}/Dockerfile"
    owner: "{{ jenkins_owner }}"
    group: "{{ jenkins_group }}"
    mode: '0644'

- name: Create directories for config files and volumes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ jenkins_home_dir }}"
    - "{{ jenkins_ssh_dir }}"

- name: Set ownership and permissions to directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: "{{ jenkins_user_id }}"
    group: "{{ jenkins_group_id }}"
    mode: '0755'
  loop:
    - "{{ jenkins_home_dir }}"
    - "{{ jenkins_ssh_dir }}"

- name: Check if iptables-persistent is installed
  ansible.builtin.apt:
    name: iptables-persistent
    state: present

- name: Launch Jenkins via docker-compose
  ansible.builtin.command:
    cmd: docker compose -f {{ jenkins_base_dir }}/docker-compose.yml up -d
    chdir: "{{ jenkins_base_dir }}"
  register: docker_compose_result
  changed_when: "'Started' in docker_compose_result.stdout or 'Creating' in docker_compose_result.stdout"

- name: Deploy slave agent start script
  ansible.builtin.template:
    dest: /usr/local/bin/start_slave_agent.sh
    src: start_slave_agent.sh.j2
    mode: '0755'

- name: Setup cron job for Jenkins Slave Agent Monitor
  ansible.builtin.cron:
    name: "Run Jenkins Slave Agent Monitor"
    minute: "{{ jenkins_slave_monitor_interval }}"
    job: "/usr/local/bin/start_slave_agent.sh"

...
